config/routes.rb
BeerLottery::Application.routes.draw do
  resources :users, :prizes
  resources :lotteries do
    get :contestants, on: :member
  end

  root :to => 'lotteries#index'

end

app/models/lottery.rb
class Lottery < ActiveRecord::Base
  attr_accessible :description, :due_at, :title, :prizes_attributes, :user_ids
  has_many :prizes
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :prizes, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  belongs_to :lottery
  attr_accessible :description, :name, :lottery_id
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :birthday, :description, :name, :nick_name, :email
  has_and_belongs_to_many :lotteries

  validates :email, :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with name: BASIC_AUTH_USR, password: BASIC_AUTH_PWD
end

app/controllers/lotteries_controller.rb
class LotteriesController < ApplicationController
  before_filter :lookup, only: [:show, :new, :edit, :update, :destroy, :contestants]
  before_filter :lottery_contestants, only: [:contestants, :show]

  # GET /lotteries
  # GET /lotteries.json
  def index
    @lotteries = Lottery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lotteries }
    end
  end

  # GET /lotteries/1
  # GET /lotteries/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lottery }
    end
  end

  # GET /lotteries/new
  # GET /lotteries/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lottery }
    end
  end

  # GET /lotteries/1/edit
  def edit
    @prizes = @lottery.prizes.new
  end

  # POST /lotteries
  # POST /lotteries.json
  def create
    @lottery = Lottery.new params[:lottery]

    respond_to do |format|
      if @lottery.save
        format.html { redirect_to @lottery, notice: 'Lottery was successfully created.' }
        format.json { render json: @lottery, status: :created, location: @lottery }
      else
        format.html { render action: "new" }
        format.json { render json: @lottery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lotteries/1
  # PUT /lotteries/1.json
  def update
    respond_to do |format|
      if @lottery.update_attributes(params[:lottery])
        format.html { redirect_to @lottery, notice: 'Lottery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lottery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotteries/1
  # DELETE /lotteries/1.json
  def destroy
    @lottery.destroy

    respond_to do |format|
      format.html { redirect_to lotteries_url }
      format.json { head :no_content }
    end
  end

  def contestants
    @users = User.all
  end


  private

  def lookup
    @lottery = params[:id] ? Lottery.find( params[:id] ) : Lottery.new
  end

  def lottery_contestants
    @contestants = @lottery.users
  end
end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
  # GET /prizes
  # GET /prizes.json
  def index
    @prizes = Prize.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prizes }
    end
  end

  # GET /prizes/1
  # GET /prizes/1.json
  def show
    @prize = Prize.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prize }
    end
  end

  # GET /prizes/new
  # GET /prizes/new.json
  def new
    @prize = Prize.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prize }
    end
  end

  # GET /prizes/1/edit
  def edit
    @prize = Prize.find(params[:id])
  end

  # POST /prizes
  # POST /prizes.json
  def create
    @prize = Prize.new(params[:prize])

    respond_to do |format|
      if @prize.save
        format.html { redirect_to @prize, notice: 'Prize was successfully created.' }
        format.json { render json: @prize, status: :created, location: @prize }
      else
        format.html { render action: "new" }
        format.json { render json: @prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prizes/1
  # PUT /prizes/1.json
  def update
    @prize = Prize.find(params[:id])

    respond_to do |format|
      if @prize.update_attributes(params[:prize])
        format.html { redirect_to @prize, notice: 'Prize was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prizes/1
  # DELETE /prizes/1.json
  def destroy
    @prize = Prize.find(params[:id])
    @prize.destroy

    respond_to do |format|
      format.html { redirect_to prizes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lotteries_helper.rb
module LotteriesHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <%= link_to 'Beer lottery', root_path, class: 'brand' %>
    <ul class="nav">
      <li><%= link_to 'Users', users_path %><li>
      <li><%= link_to 'Lotteries', lotteries_path %><li>
      <li><%= link_to 'Prizes', prizes_path %><li>
    </ul>
  </div>
</div>

app/views/layouts/_object_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this
      <%= object.class.name.downcase %> from being saved:</h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerLottery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
<div class="container">
  <%= render 'layouts/header' %>
  <%= yield %>
</div>
</body>
</html>

app/views/lotteries/_form.html.erb
<%= form_for(@lottery) do |f| %>
  <%= render 'layouts/object_errors', object: @lottery %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :due_at %>
    <%= f.date_select :due_at %>
  </div>

  <% unless %w( new create ).include? action_name %>
    <h3>Prizes</h3>
    <%= f.fields_for :prizes do |builder| %>
      <div class="field">
        <%= builder.label :name %>
        <%= builder.text_field :name %>
        <%= builder.check_box :_destroy %> Remove
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lotteries/contestants.html.erb
<h1><%= @lottery.title %></h1>
<h2>Contestants</h2>

<%= form_for @lottery do |f| %>
  <div class="field">
    <%= f.label :user_ids, 'Disse er med' %>
    <%= f.collection_select :user_ids, @users, :id, :name,
          {}, size: 10, multiple: true %>
  </div>

  <%= f.submit %>
<% end %>

app/views/lotteries/edit.html.erb
<h1>Editing lottery</h1>

<%= render 'form' %>

<%= link_to 'Show', @lottery %> |
<%= link_to 'All lotteries', lotteries_path %>

app/views/lotteries/index.html.erb
<h1>Listing lotteries</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th><%= t('activerecord.attributes.lottery.description') %></th>
    <th>Due at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lotteries.each do |lottery| %>
  <tr>
    <td><%= lottery.title %></td>
    <td><%= lottery.description %></td>
    <td><%= lottery.due_at %></td>
    <td><%= link_to 'Show', lottery %></td>
    <td><%= link_to 'Edit', edit_lottery_path(lottery) %></td>
    <td><%= link_to 'Destroy', lottery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lottery', new_lottery_path %>

app/views/lotteries/new.html.erb
<h1>New lottery</h1>

<%= render 'form' %>

<%= link_to 'All lotteries', lotteries_path %>

app/views/lotteries/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @lottery.title %></h1>

<p>
  <b>Description:</b>
  <%= @lottery.description %>
</p>

<p>
  <b>Due at:</b>
  <%= @lottery.due_at %>
</p>

<h2>Contestants</h2>
<ul>
  <% @contestants.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>
<p><%= link_to 'Add or remove', contestants_lottery_path( @lottery )%></p>

<% unless @lottery.prizes.empty? %>
  <h2>Prizes</h2>
  <ul>
    <% @lottery.prizes.each do |prize| %>
      <li><%= prize.name %> <%= link_to 'edit', edit_prize_path( prize ) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Add new prizes', edit_lottery_path( @lottery ) %>

<p><%= link_to 'Edit lottery', edit_lottery_path(@lottery) %> |
<%= link_to 'All lotteries', lotteries_path %></p>

app/views/prizes/_form.html.erb
<%= form_for(@prize) do |f| %>
  <% if @prize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prize.errors.count, "error") %> prohibited this prize from being saved:</h2>

      <ul>
      <% @prize.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 4 %>
  </div>
  <%= f.hidden_field :lottery_id, value: @prize.lottery_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prizes/edit.html.erb
<h1>Editing prize</h1>

<%= render 'form' %>

<%= link_to 'Show', @prize %> |
<%= link_to 'All prizes', prizes_path %>

app/views/prizes/index.html.erb
<h1>Listing prizes</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Lottery</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prizes.each do |prize| %>
  <tr>
    <td><%= prize.name %></td>
    <td><%= prize.description %></td>
    <td><%= prize.lottery.title %></td>
    <td><%= link_to 'Show', prize %></td>
    <td><%= link_to 'Edit', edit_prize_path(prize) %></td>
    <td><%= link_to 'Destroy', prize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<div class="alert alert-info">
  <strong>Note!</strong> New prizes are added on the edit lottery page
</div>

app/views/prizes/new.html.erb
<h1>New prize</h1>

<%= render 'form' %>

<%= link_to 'Back', prizes_path %>

app/views/prizes/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @prize.name %></h1>

<p>
  <b>Description:</b>
  <%= @prize.description %>
</p>

<p>
  <b>Lottery:</b>
  <%= @prize.lottery.title %>
</p>


<%= link_to 'Edit prize', edit_prize_path(@prize) %> |
<%= link_to 'All prizes', prizes_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'layouts/object_errors', object: @user %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nick_name %>
    <%= f.text_field :nick_name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday, start_year: 1950, end_year: Time.now.year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Nick name</th>
    <th>Email</th>
    <th>Description</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.nick_name %></td>
    <td><%= user.email %></td>
    <td><%= user.description %></td>
    <td><%= user.birthday %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %></h1>

<p>
  <b>Nick name:</b>
  <%= @user.nick_name %>
</p>

<p>
  <b>Description:</b>
  <%= @user.description %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<h2>Lotteries</h2>
<ul>
  <% @user.lotteries.each do |lottery| %>
    <li><%= lottery.title %></li>
  <% end %>
</li>

<%= link_to 'Edit user', edit_user_path(@user) %> |
<%= link_to 'All users', users_path %>